apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: uit-go-app
type: Opaque
stringData:
  POSTGRES_DB: uitgo_userdb
  POSTGRES_USER: uitgo_user
  POSTGRES_PASSWORD: uitgo_password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: uit-go-app
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: uit-go-app
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
