apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: uit-go-app
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: postgresql
        image: bitnamilegacy/postgresql:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 40
          periodSeconds: 20
        volumeMounts:
        - name: postgres-data
          mountPath: /bitnami/postgresql
        - name: postgres-conf
          mountPath: /opt/bitnami/postgresql/conf
        - name: postgres-tmp
          mountPath: /opt/bitnami/postgresql/tmp
      volumes:
      - name: postgres-data
        emptyDir: {}
      - name: postgres-conf
        emptyDir: {}
      - name: postgres-tmp
        emptyDir: {}
